# Generated by Django 5.0.7 on 2024-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_order_items_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_product_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
