# Generated by Django 5.0.7 on 2024-10-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_total_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_co2_footprint',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
