# Generated by Django 5.0.7 on 2024-10-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_has_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
