# Generated by Django 5.0.7 on 2024-10-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_options',
        ),
    ]
