# Generated by Django 5.0.7 on 2024-10-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_has_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
