# Generated by Django 5.0.7 on 2024-10-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_rating_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
