# Generated by Django 5.0.7 on 2024-10-18 18:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/drrywrvwv/image/upload/v1729274738/background_small_uxkai1.jpg', max_length=255, verbose_name='image'),
        ),
    ]
