# Generated by Django 5.0.7 on 2024-10-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
